/*
 *  Copyright 2008 Alessandro Pilotti
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA 
 */

namespace AlexPilotti.FTPS.Common
{
    using System;

    /// <summary>
    /// Base FTP exception class.
    /// </summary>
    public class FTPException : Exception
    {
        /// <inheritdoc />
        protected FTPException()
        {
        }

        /// <inheritdoc />
        public FTPException(string message)
            : base(message)
        {
        }

        /// <inheritdoc />
        public FTPException(string message, Exception innerException)
            : base(message, innerException)
        {
        }
    }

    /// <inheritdoc />
    public class FTPReplyParseException : FTPException
    {
        /// <summary>
        /// 
        /// </summary>
        public string ReplyText { get; }

        /// <inheritdoc />
        public FTPReplyParseException(string replyText)
            : base("Invalid server reply: " + replyText)
        {
            ReplyText = replyText;
        }
    }

    /// <inheritdoc />
    public class FTPProtocolException : FTPException
    {
        /// <summary>
        /// 
        /// </summary>
        public FTPReply Reply { get; }

        /// <inheritdoc />
        public FTPProtocolException(FTPReply reply) : base("Invalid FTP protocol reply: " + reply)
        {
            Reply = reply;
        }
    }

    /// <summary>
    /// Exception indicating that a command or set of commands have been cancelled by the caller, via a callback method or event.
    /// </summary>
    public class FTPOperationCancelledException : FTPException
    {
        /// <inheritdoc />
        public FTPOperationCancelledException(string message)
            : base(message)
        {
        }
    }

    /// <summary>
    /// FTP exception generated by a command with a return code >= 400, as stated in RFC 959.
    /// </summary>
    public class FTPCommandException : FTPException
    {
        /// <summary>
        /// 
        /// </summary>
        public int ErrorCode { get; }

        /// <inheritdoc />
        public FTPCommandException(string message)
            : base(message)
        {
        }

        /// <inheritdoc />
        public FTPCommandException(string message, Exception innerException)
            : base(message, innerException)
        {
        }

        /// <inheritdoc />
        public FTPCommandException(FTPReply reply)
            : base(reply.Message)
        {
            ErrorCode = reply.Code;
        }
    }

    /// <summary>
    /// FTP exception related to the SSL/TLS support
    /// </summary>
    public class FTPSslException : FTPException
    {
        /// <inheritdoc />
        public FTPSslException(string message)
            : base(message)
        {
        }

        /// <inheritdoc />
        public FTPSslException(string message, Exception innerException)
            : base(message, innerException)
        {
        }
    }
}
